version: "3.8"
services:
    nginx:
        image: nginx:stable-alpine3.17-perl
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - task-0-6-network
        restart: always

    sre-web:
        image: zhongkuo/sre-web:task-0-6
        ports:
            - "13000:3000"
        depends_on:
            - sre-db
            - redis
        networks:
            - task-0-6-network
        restart: always

    sre-db:
        image: zhongkuo/sre-db:task-0-6v2
        ports:
            - "13306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - task-0-6-network
        restart: always

    redis:
        image: redis
        ports:
            - "16379:6379"
        volumes:
            - redis-data:/data
        networks:
            - task-0-6-network
        restart: always

volumes:
    mysql-data:
    redis-data:

networks:
    task-0-6-network:
